In [1]:
import pennylane as qml
from pennylane import numpy as np

In [56]:
dev = qml.device("default.qubit")

def W(params):
    (_, n_qubits) = np.shape(params)
    qml.BasicEntanglerLayers(weights=params, wires=range(n_qubits), rotation=qml.RY)

def S(g, x, num_wires):
    for i in range(num_wires):
        qml.exp(g(i),-1.0j * x)

@qml.qnode(dev)
def quantum_model(param_set, g, x):
    (n_train, _, n_qubits) = np.shape(param_set)
    for i in range(n_train-1):
        W(param_set[i])
        S(g,x,n_qubits)

    W(param_set[n_train-1])
    return qml.probs(wires=0)
        

In [59]:
params = [[[1.0472, 0.7854, 3.1416, 0.3927],
           [1.0472, 0.7854, 3.1416, 0.5236]],
          [[1.0472, 0.7854, 1.5708, 0.3927],
           [0.7854, 0.7854, 1.5708, 0.7854]]]
gate = qml.X
gate_param = 0.7854

print(quantum_model(params, gate, gate_param))
print(qml.draw(quantum_model)(params, gate, gate_param))

[0.46652954 0.53347046]
0: ─╭BasicEntanglerLayers(M0)──Exp(0.00-0.79j X)─╭BasicEntanglerLayers(M1)─┤  Probs
1: ─├BasicEntanglerLayers(M0)──Exp(0.00-0.79j X)─├BasicEntanglerLayers(M1)─┤       
2: ─├BasicEntanglerLayers(M0)──Exp(0.00-0.79j X)─├BasicEntanglerLayers(M1)─┤       
3: ─╰BasicEntanglerLayers(M0)──Exp(0.00-0.79j X)─╰BasicEntanglerLayers(M1)─┤       

M0 = 
[[1.0472 0.7854 3.1416 0.3927]
 [1.0472 0.7854 3.1416 0.5236]]
M1 = 
[[1.0472 0.7854 1.5708 0.3927]
 [0.7854 0.7854 1.5708 0.7854]]
